services:
  firebase-emulator:
    build: ./firebase-emulator
    volumes:
      - ./firebase-emulator/firebase-export:/app/firebase-export
    ports:
      - "4000:4000"
      - "9099:9099"
      - "8088:8088"
      - "9199:9199"
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "9150"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgresdb:
    image: postgres:18-alpine
    volumes:
      - postgres_data:/var/lib/postgresql
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  config-server:
    build: ./config-server
    ports:
      - "8888:8888"
    environment:
      CONFIG_REPO_URL: https://github.com/pgr866/msc-soccer-project-config
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "8888"]
      interval: 10s
      timeout: 5s
      retries: 5

  eureka-server:
    build: ./eureka-server
    ports:
      - "8761:8761"
    environment:
      CONFIG_SERVER_URL: http://config-server:8888
    depends_on:
      config-server:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "8761"]
      interval: 10s
      timeout: 5s
      retries: 5

  gateway:
    build: ./gateway
    ports:
      - "8080:8080"
    environment:
      CONFIG_SERVER_URL: http://config-server:8888
      EUREKA_SERVER_URL: http://eureka-server:8761/eureka/
      FIREBASE_AUTH_EMULATOR_HOST: firebase-emulator:9099
      FIRESTORE_EMULATOR_HOST: firebase-emulator:8088
    depends_on:
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
      firebase-emulator:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "8080"]
      interval: 10s
      timeout: 5s
      retries: 5

  player-service:
    build: ./player-service
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8081:8081"
    environment:
      CONFIG_SERVER_URL: http://config-server:8888
      EUREKA_SERVER_URL: http://eureka-server:8761/eureka/
      CORBA_APP_URL: http://corba-app:8084
      SB_DB_HOST: postgresdb
      SB_DB_PORT: 5432
      SB_DB_NAME: postgres
      SB_DB_USER: user
      SB_DB_PASSWORD: password
      FOOTBALL_API_KEY: ${FOOTBALL_API_KEY}
    depends_on:
      postgresdb:
        condition: service_healthy
      firebase-emulator:
        condition: service_healthy
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "8081"]
      interval: 10s
      timeout: 5s
      retries: 5

  comment-service:
    build: ./comment-service
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8082:8082"
    environment:
      CONFIG_SERVER_URL: http://config-server:8888
      EUREKA_SERVER_URL: http://eureka-server:8761/eureka/
      SB_DB_HOST: postgresdb
      SB_DB_PORT: 5432
      SB_DB_NAME: postgres
      SB_DB_USER: user
      SB_DB_PASSWORD: password
    depends_on:
      postgresdb:
        condition: service_healthy
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "8082"]
      interval: 10s
      timeout: 5s
      retries: 5

  dream-team-service:
    build: ./dream-team-service
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8083:8083"
    environment:
      CONFIG_SERVER_URL: http://config-server:8888
      EUREKA_SERVER_URL: http://eureka-server:8761/eureka/
      SB_DB_HOST: postgresdb
      SB_DB_PORT: 5432
      SB_DB_NAME: postgres
      SB_DB_USER: user
      SB_DB_PASSWORD: password
      GROQ_API_KEY: ${GROQ_API_KEY}
    depends_on:
      postgresdb:
        condition: service_healthy
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "8083"]
      interval: 10s
      timeout: 5s
      retries: 5

  corba-app:
    build: corba-app
    container_name: corba-app
    restart: always
    ports:
      - "8084:8084"
    environment:
      CLIENT_CORBA_PORT: 8084
      ORB_CORBA_PORT: 1050
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "8084"]
      interval: 10s
      timeout: 5s
      retries: 5

  mongodb:
    image: mongo:7.0.34-jammy
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
    healthcheck:
      test: ["CMD-SHELL", "mongosh --quiet --eval 'db.runCommand(\"ping\").ok'"]
      interval: 10s
      timeout: 5s
      retries: 5

  node-api:
    build:
      context: ./node-api
      target: development
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./node-api:/app
      - node-cache:/app/node_modules
    ports:
      - "3000:3000"
    environment:
      FIREBASE_AUTH_EMULATOR_HOST: firebase-emulator:9099
      FIRESTORE_EMULATOR_HOST: firebase-emulator:8088
      CORBA_APP_URL: http://corba-app:8084
      MDB_DB_USER: user
      MDB_DB_PASSWORD: password
      MDB_DB_HOST: mongodb
      MDB_DB_NAME: mongo
      MDB_DB_PORT: 27017
      FOOTBALL_API_KEY: ${FOOTBALL_API_KEY}
      GROQ_API_KEY: ${GROQ_API_KEY}
    depends_on:
      mongodb:
        condition: service_healthy
      firebase-emulator:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "3000"]
      interval: 10s
      timeout: 5s
      retries: 5

  ionic-app:
    build:
      context: ./ionic-app
      target: development
    volumes:
      - ./ionic-app:/app
      - ionic-cache:/app/node_modules
      - angular-cache:/app/.angular
    ports:
      - "8100:8100"
    depends_on:
      firebase-emulator:
        condition: service_healthy

  # cypress:
  #   image: cypress/included:15.15.0
  #   network_mode: "host"
  #   environment:
  #     - DISPLAY=$DISPLAY
  #     - XDG_RUNTIME_DIR=$XDG_RUNTIME_DIR
  #     - ELECTRON_OZONE_PLATFORM_HINT=wayland
  #   volumes:
  #     - ./ionic-app:/app
  #     - ionic-cache:/app/node_modules
  #     - $XDG_RUNTIME_DIR/$WAYLAND_DISPLAY:$XDG_RUNTIME_DIR/$WAYLAND_DISPLAY
  #   working_dir: /app
  #   entrypoint: npx cypress open --project .

volumes:
  postgres_data:
  mongo-data:
  node-cache:
  ionic-cache:
  angular-cache:
