server {
    listen 8100;
    root /usr/share/nginx/html;
    index index.html;
    client_body_temp_path /tmp/client_temp;
    proxy_temp_path /tmp/proxy_temp;
    fastcgi_temp_path /tmp/fastcgi_temp;
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-XSS-Protection "1; mode=block" always;
    location ~ /\. {
        deny all;
    }
    location / {
        try_files $uri $uri/ /index.html;
    }
}
