/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface PlayerDetail {
        "playerDetail": any;
    }
    interface PlayersList {
        /**
          * @default []
         */
        "players": any[];
    }
}
export interface PlayerDetailCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLPlayerDetailElement;
}
export interface PlayersListCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLPlayersListElement;
}
declare global {
    interface HTMLPlayerDetailElementEventMap {
        "closeDetail": void;
    }
    interface HTMLPlayerDetailElement extends Components.PlayerDetail, HTMLStencilElement {
        addEventListener<K extends keyof HTMLPlayerDetailElementEventMap>(type: K, listener: (this: HTMLPlayerDetailElement, ev: PlayerDetailCustomEvent<HTMLPlayerDetailElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLPlayerDetailElementEventMap>(type: K, listener: (this: HTMLPlayerDetailElement, ev: PlayerDetailCustomEvent<HTMLPlayerDetailElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLPlayerDetailElement: {
        prototype: HTMLPlayerDetailElement;
        new (): HTMLPlayerDetailElement;
    };
    interface HTMLPlayersListElementEventMap {
        "playerSelected": string;
    }
    interface HTMLPlayersListElement extends Components.PlayersList, HTMLStencilElement {
        addEventListener<K extends keyof HTMLPlayersListElementEventMap>(type: K, listener: (this: HTMLPlayersListElement, ev: PlayersListCustomEvent<HTMLPlayersListElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLPlayersListElementEventMap>(type: K, listener: (this: HTMLPlayersListElement, ev: PlayersListCustomEvent<HTMLPlayersListElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLPlayersListElement: {
        prototype: HTMLPlayersListElement;
        new (): HTMLPlayersListElement;
    };
    interface HTMLElementTagNameMap {
        "player-detail": HTMLPlayerDetailElement;
        "players-list": HTMLPlayersListElement;
    }
}
declare namespace LocalJSX {
    interface PlayerDetail {
        "onCloseDetail"?: (event: PlayerDetailCustomEvent<void>) => void;
        "playerDetail"?: any;
    }
    interface PlayersList {
        "onPlayerSelected"?: (event: PlayersListCustomEvent<string>) => void;
        /**
          * @default []
         */
        "players"?: any[];
    }

    interface PlayerDetailAttributes {
        "playerDetail": string;
    }

    interface IntrinsicElements {
        "player-detail": Omit<PlayerDetail, keyof PlayerDetailAttributes> & { [K in keyof PlayerDetail & keyof PlayerDetailAttributes]?: PlayerDetail[K] } & { [K in keyof PlayerDetail & keyof PlayerDetailAttributes as `attr:${K}`]?: PlayerDetailAttributes[K] } & { [K in keyof PlayerDetail & keyof PlayerDetailAttributes as `prop:${K}`]?: PlayerDetail[K] };
        "players-list": PlayersList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "player-detail": LocalJSX.IntrinsicElements["player-detail"] & JSXBase.HTMLAttributes<HTMLPlayerDetailElement>;
            "players-list": LocalJSX.IntrinsicElements["players-list"] & JSXBase.HTMLAttributes<HTMLPlayersListElement>;
        }
    }
}
